import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Providers } from "./redux/provider";
import ProviderData from "./provider-data";
import { getSession } from "./utils/session";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

interface LProps {
  children: React.ReactNode
}

export default async function RootLayout({children}: Readonly<LProps>) {
  const session = await getSession();

  return (
    <Providers>
      <ProviderData session={session}>
        <html lang="en" data-theme="light">
          <body className={inter.className}>{children}</body>
        </html>
      </ProviderData>
    </Providers>
  );
}
